/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-14 02:02:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.EscolaSambaDAO;
import negocio.EscolaSamba;
import negocio.Entidade;

public final class CadastroTorcedor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Cadastro de Torcedor</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");

String oAcao = "salvar";
String oSucesso = "";

if(request.getAttribute("oAcao") != null)
{
	oAcao = request.getAttribute("oAcao").toString();
}

if(request.getAttribute("oSucesso") != null)
{
	oSucesso = request.getAttribute("oSucesso").toString();
}

      out.write("\n");
      out.write("\n");
      out.write("\t<script language=\"Javascript\" type=\"text/javascript\">\n");
      out.write("\t\tvar sucesso = \"");
      out.print(oSucesso);
      out.write("\";\n");
      out.write("\t\tif(sucesso != \"\")\n");
      out.write("\t\t{\n");
      out.write("\t\t\tif(sucesso == \"s\")\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\talert(\"Cadastro efetuado com sucesso\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\talert(\"Houve uma falha no seu cadastro. Tente novamente.\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<form action=\"ControlaTorcedor\" method=\"post\">\n");
      out.write("\t\n");
      out.write("\t\t<input type=\"hidden\" name=\"acao\" value=\"salvar\">\n");
      out.write("\t\n");
      out.write("\t\t<h2>Cadastro de Torcedor</h2>\n");
      out.write("\t\n");
      out.write("\t\t<h3>Nome</h3><input type=\"text\" name=\"nome\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>CPF</h3><input type=\"text\" name=\"cpf\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Endereço</h3><input type=\"text\" name=\"endereco\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Cep</h3><input type=\"text\" name=\"cep\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Sexo</h3>\n");
      out.write("\t\t\n");
      out.write("\t\t<input name=sexos list=\"sexos\">\n");
      out.write(" \t\t<datalist id=\"sexos\">\n");
      out.write("\t\t\t<option value=\"Masculino\">\n");
      out.write("\t\t\t<option value=\"Feminino\">\n");
      out.write("\t\t</datalist>\n");
      out.write("\n");
      out.write("\t\t<h3>Email</h3><input type=\"text\" name=\"email\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Telefone</h3><input type=\"text\" name=\"telefone\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Escola de Samba do Coração</h3>\n");
      out.write("\t\t<input name=escolaSamba list=\"escolaSamba\">\n");
      out.write("\t\t<datalist id=\"escolaSamba\">\n");
      out.write("\t\t");

			for ( Entidade e : new EscolaSambaDAO().obterTodosCollection() ) {
				EscolaSamba t = (EscolaSamba) e;
					out.println( "<option value=\"" + t.getNome() + "\">" );
			}
		
      out.write("\n");
      out.write("\t\t</datalist>\n");
      out.write("\n");
      out.write("\t\t<h3>Login</h3><input type=\"text\" name=\"login\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Senha</h3><input type=\"text\" name=\"senha\">\n");
      out.write("\n");
      out.write("\t\t<br/>\n");
      out.write("\t\t<br/>\n");
      out.write("\n");
      out.write("\t\t<input type=\"submit\" value=\"Salvar e Continuar\">\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
