/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-04-30 01:04:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.EscolaSambaDAO;
import dao.TorcedorDAO;
import negocio.EscolaSamba;
import negocio.Torcedor;
import negocio.Entidade;

public final class ConsultaEscola_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");

	EscolaSamba escola = (EscolaSamba) new EscolaSambaDAO().obterPorId( Integer.decode( request.getParameter("idEscola" ) ) );

      out.write("\n");
      out.write("<title>Escola de samba:");
      out.print(escola.getNome());
      out.write(" </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<fieldset>\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"nome\">Nome</label>\n");
      out.write("\t\t\t\t<input name= \"nome\" value=\"");
      out.print(escola.getNome());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"enderecoQuadra\">Endereço de quadra</label>\n");
      out.write("\t\t\t\t<input name= \"enderecoQuadra\" value=\"");
      out.print(escola.getEnderecoQuadra());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"enderecoBarracao\">Endereço de barracão</label>\n");
      out.write("\t\t\t\t<input name= \"enderecoBarracao\" value=\"");
      out.print(escola.getEnderecoBarracao());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"lema\">Lema</label>\n");
      out.write("\t\t\t\t<input name= \"lema\" value=\"");
      out.print(escola.getLema());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"filiacao\">Filiação</label>\n");
      out.write("\t\t\t\t<input name= \"filiacao\" value=\"");
      out.print(escola.getFiliacao());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"grupo\">Grupo atual</label>\n");
      out.write("\t\t\t\t<input name= \"grupo\" value=\"");
      out.print(escola.getGrupoAtual());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"email\">Email</label>\n");
      out.write("\t\t\t\t<input name= \"email\" value=\"");
      out.print(escola.getEmail());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"telefone\">Telefone</label>\n");
      out.write("\t\t\t\t<input name= \"telefone\" value=\"");
      out.print(escola.getTelefone());
      out.write("\" />\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label for=\"cnpj\">CNPJ</label>\n");
      out.write("\t\t\t\t<input name= \"cnpj\" value=\"");
      out.print(escola.getCnpj());
      out.write("\" />\n");
      out.write("\t\t\t</li>\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t</fieldset>\n");
      out.write("\t\n");
      out.write("\t<section id = \"torcedores\">\n");
      out.write("\t<h2>torcedores:</h2>\n");
      out.write("\t<ul>\n");
      out.write("\t\t");

			for ( Entidade e : new TorcedorDAO().obterTodosCollection() ) {
				Torcedor t = (Torcedor) e;
				if ( t.getEscolaSamba() == escola ) {
					out.println( "<li><a href='ConsultaTorcedor?idTorcedor=" + t.getId() + "'>" + t.getNome() + "</a></li>" );
				}
			}
		
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t</section>\n");
      out.write("\t<hr />\n");
      out.write("\t<a href=\"#\" onclick=\"window.history.back()\">Voltar</a>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
